{% set name = "dvc-studio-client" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 45d554a0386dd18bdfe17968e93f9b075563c888088b51bfa58713f64ed58ac8

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - dulwich
    - python >={{ python_min }}
    - requests
    - voluptuous

test:
  imports:
    - dvc_studio_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iterative/dvc-studio-client
  summary: Small library to post data from DVC/DVCLive to Iterative Studio
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daavoo
    - efiop
    - shcheklein
