{% set name = "dvc-studio-client" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dvc-studio-client-{{ version }}.tar.gz
  sha256: abaadc92126aca874efb177c664a1cdf6e0c642435c51c7187a03b433cbc3472

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - dulwich
    - python >=3.8
    - requests
    - voluptuous

test:
  imports:
    - dvc_studio_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iterative/dvc-studio-client
  summary: Small library to post data from DVC/DVCLive to Iterative Studio
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daavoo
    - efiop
    - shcheklein
