{% set name = "dvc-studio-client" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dvc-studio-client-{{ version }}.tar.gz
  sha256: 110097f39970bbb8f14f9c26e730d8d1fa3d5c3928d6ec6ccdadd86769049f4c

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - dulwich
    - python >=3.8
    - requests
    - voluptuous

test:
  imports:
    - dvc_studio_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iterative/dvc-studio-client
  summary: Small library to post data from DVC/DVCLive to Iterative Studio
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daavoo
    - efiop
    - shcheklein
